[orcalab]
pak_urls = [ "https://orcalab-open.oss-cn-shanghai.aliyuncs.com/orcalab_linux.26.7.1.5.pak",]
python_project_url = "https://orcalab-open.oss-cn-shanghai.aliyuncs.com/python-project_linux.26.7.1.5.tar.xz"
version = "26.7.1.5"
pak_urls_sha256 = [ "2a38a59f0ab37163675b7de57089cdff32c5951c856a207fbce75f36c92d2080",]
python_project_sha256 = "ec243594d31ee95a00fbfb7f9ae5d46359933c7bde75b1ec4f0630c463ffdbd5"
