[orcalab]
pak_urls = [ "https://orcalab-open.oss-cn-shanghai.aliyuncs.com/orcalab_pc.26.7.1.9.pak",]
python_project_url = "https://orcalab-open.oss-cn-shanghai.aliyuncs.com/python-project_pc.26.7.1.9.tar.xz"
version = "26.7.1.9"
pak_urls_sha256 = [ "028e36b1ae9cf070d92a8220f62e8be93dbc0b380e24d9923a46f9c534b678a6",]
python_project_sha256 = "eeb1313d851b71ce218a1d82d2827f487676f0c46dbbc7f02a0bce34b8b931e9"
