# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import edit_service_pb2 as edit__service__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in edit_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Aloha = channel.unary_unary(
                '/SceneEdit.GrpcService/Aloha',
                request_serializer=edit__service__pb2.AlohaRequest.SerializeToString,
                response_deserializer=edit__service__pb2.AlohaResponse.FromString,
                _registered_method=True)
        self.AddActorBatch = channel.unary_unary(
                '/SceneEdit.GrpcService/AddActorBatch',
                request_serializer=edit__service__pb2.AddActorBatchRequest.SerializeToString,
                response_deserializer=edit__service__pb2.AddActorBatchResponse.FromString,
                _registered_method=True)
        self.DeleteActorBatch = channel.unary_unary(
                '/SceneEdit.GrpcService/DeleteActorBatch',
                request_serializer=edit__service__pb2.DeleteActorBatchRequest.SerializeToString,
                response_deserializer=edit__service__pb2.DeleteActorBatchResponse.FromString,
                _registered_method=True)
        self.GetPendingOperations = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPendingOperations',
                request_serializer=edit__service__pb2.GetPendingOperationsRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPendingOperationsResponse.FromString,
                _registered_method=True)
        self.GetPendingActorTransformBatch = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPendingActorTransformBatch',
                request_serializer=edit__service__pb2.GetPendingActorTransformBatchRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPendingActorTransformBatchResponse.FromString,
                _registered_method=True)
        self.SetActorTransformBatch = channel.unary_unary(
                '/SceneEdit.GrpcService/SetActorTransformBatch',
                request_serializer=edit__service__pb2.SetActorTransformBatchRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetActorTransformBatchResponse.FromString,
                _registered_method=True)
        self.GetSyncFromMujocoToScene = channel.unary_unary(
                '/SceneEdit.GrpcService/GetSyncFromMujocoToScene',
                request_serializer=edit__service__pb2.GetSyncFromMujocoToSceneRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetSyncFromMujocoToSceneResponse.FromString,
                _registered_method=True)
        self.SetSyncFromMujocoToScene = channel.unary_unary(
                '/SceneEdit.GrpcService/SetSyncFromMujocoToScene',
                request_serializer=edit__service__pb2.SetSyncFromMujocoToSceneRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetSyncFromMujocoToSceneResponse.FromString,
                _registered_method=True)
        self.ClearScene = channel.unary_unary(
                '/SceneEdit.GrpcService/ClearScene',
                request_serializer=edit__service__pb2.ClearSceneRequest.SerializeToString,
                response_deserializer=edit__service__pb2.ClearSceneResponse.FromString,
                _registered_method=True)
        self.GetActorAssets = channel.unary_unary(
                '/SceneEdit.GrpcService/GetActorAssets',
                request_serializer=edit__service__pb2.GetActorAssetsRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetActorAssetsResponse.FromString,
                _registered_method=True)
        self.GetPendingSelectionChange = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPendingSelectionChange',
                request_serializer=edit__service__pb2.GetPendingSelectionChangeRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPendingSelectionChangeResponse.FromString,
                _registered_method=True)
        self.GetPendingAddItem = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPendingAddItem',
                request_serializer=edit__service__pb2.GetPendingAddItemRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPendingAddItemResponse.FromString,
                _registered_method=True)
        self.SetSelection = channel.unary_unary(
                '/SceneEdit.GrpcService/SetSelection',
                request_serializer=edit__service__pb2.SetSelectionRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetSelectionResponse.FromString,
                _registered_method=True)
        self.SaveState = channel.unary_unary(
                '/SceneEdit.GrpcService/SaveState',
                request_serializer=edit__service__pb2.SaveStateRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SaveStateResponse.FromString,
                _registered_method=True)
        self.RestoreState = channel.unary_unary(
                '/SceneEdit.GrpcService/RestoreState',
                request_serializer=edit__service__pb2.RestoreStateRequest.SerializeToString,
                response_deserializer=edit__service__pb2.RestoreStateResponse.FromString,
                _registered_method=True)
        self.RenameActor = channel.unary_unary(
                '/SceneEdit.GrpcService/RenameActor',
                request_serializer=edit__service__pb2.RenameActorRequest.SerializeToString,
                response_deserializer=edit__service__pb2.RenameActorResponse.FromString,
                _registered_method=True)
        self.MoveActorBatch = channel.unary_unary(
                '/SceneEdit.GrpcService/MoveActorBatch',
                request_serializer=edit__service__pb2.MoveActorBatchRequest.SerializeToString,
                response_deserializer=edit__service__pb2.MoveActorBatchResponse.FromString,
                _registered_method=True)
        self.GetWindowId = channel.unary_unary(
                '/SceneEdit.GrpcService/GetWindowId',
                request_serializer=edit__service__pb2.GetWindowIdRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetWindowIdResponse.FromString,
                _registered_method=True)
        self.GetGeneratePos = channel.unary_unary(
                '/SceneEdit.GrpcService/GetGeneratePos',
                request_serializer=edit__service__pb2.GetGeneratePosRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetGeneratePosResponse.FromString,
                _registered_method=True)
        self.GetCacheFolder = channel.unary_unary(
                '/SceneEdit.GrpcService/GetCacheFolder',
                request_serializer=edit__service__pb2.GetCacheFolderRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetCacheFolderResponse.FromString,
                _registered_method=True)
        self.LoadPackage = channel.unary_unary(
                '/SceneEdit.GrpcService/LoadPackage',
                request_serializer=edit__service__pb2.LoadPackageRequest.SerializeToString,
                response_deserializer=edit__service__pb2.LoadPackageResponse.FromString,
                _registered_method=True)
        self.ChangeSimState = channel.unary_unary(
                '/SceneEdit.GrpcService/ChangeSimState',
                request_serializer=edit__service__pb2.ChangeSimStateRequest.SerializeToString,
                response_deserializer=edit__service__pb2.ChangeSimStateResponse.FromString,
                _registered_method=True)
        self.ChangeManipulatorType = channel.unary_unary(
                '/SceneEdit.GrpcService/ChangeManipulatorType',
                request_serializer=edit__service__pb2.ChangeManipulatorTypeRequest.SerializeToString,
                response_deserializer=edit__service__pb2.ChangeManipulatorTypeResponse.FromString,
                _registered_method=True)
        self.GetCameraPNG = channel.unary_unary(
                '/SceneEdit.GrpcService/GetCameraPNG',
                request_serializer=edit__service__pb2.GetCameraPNGRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetCameraPNGResponse.FromString,
                _registered_method=True)
        self.GetActorAssetAabb = channel.unary_unary(
                '/SceneEdit.GrpcService/GetActorAssetAabb',
                request_serializer=edit__service__pb2.GetActorAssetAabbRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetActorAssetAabbResponse.FromString,
                _registered_method=True)
        self.QueueMouseEvent = channel.unary_unary(
                '/SceneEdit.GrpcService/QueueMouseEvent',
                request_serializer=edit__service__pb2.QueueMouseEventRequest.SerializeToString,
                response_deserializer=edit__service__pb2.QueueMouseEventResponse.FromString,
                _registered_method=True)
        self.QueueMouseWheelEvent = channel.unary_unary(
                '/SceneEdit.GrpcService/QueueMouseWheelEvent',
                request_serializer=edit__service__pb2.QueueMouseWheelEventRequest.SerializeToString,
                response_deserializer=edit__service__pb2.QueueMouseWheelEventResponse.FromString,
                _registered_method=True)
        self.QueueKeyEvent = channel.unary_unary(
                '/SceneEdit.GrpcService/QueueKeyEvent',
                request_serializer=edit__service__pb2.QueueKeyEventRequest.SerializeToString,
                response_deserializer=edit__service__pb2.QueueKeyEventResponse.FromString,
                _registered_method=True)
        self.GetCameras = channel.unary_unary(
                '/SceneEdit.GrpcService/GetCameras',
                request_serializer=edit__service__pb2.GetCamerasRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetCamerasResponse.FromString,
                _registered_method=True)
        self.GetActiveCamera = channel.unary_unary(
                '/SceneEdit.GrpcService/GetActiveCamera',
                request_serializer=edit__service__pb2.GetActiveCameraRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetActiveCameraResponse.FromString,
                _registered_method=True)
        self.SetActiveCamera = channel.unary_unary(
                '/SceneEdit.GrpcService/SetActiveCamera',
                request_serializer=edit__service__pb2.SetActiveCameraRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetActiveCameraResponse.FromString,
                _registered_method=True)
        self.GetViewportCameraTransform = channel.unary_unary(
                '/SceneEdit.GrpcService/GetViewportCameraTransform',
                request_serializer=edit__service__pb2.GetViewportCameraTransformRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetViewportCameraTransformResponse.FromString,
                _registered_method=True)
        self.GetCameraDataPNG = channel.unary_unary(
                '/SceneEdit.GrpcService/GetCameraDataPNG',
                request_serializer=edit__service__pb2.GetCameraDataPNGRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetCameraDataPNGResponse.FromString,
                _registered_method=True)
        self.GetPropertyGroups = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPropertyGroups',
                request_serializer=edit__service__pb2.GetPropertyGroupsRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPropertyGroupsResponse.FromString,
                _registered_method=True)
        self.GetPropertyGroupsBatch = channel.unary_unary(
                '/SceneEdit.GrpcService/GetPropertyGroupsBatch',
                request_serializer=edit__service__pb2.GetPropertyGroupsBatchRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPropertyGroupsBatchResponse.FromString,
                _registered_method=True)
        self.GetProperties = channel.unary_unary(
                '/SceneEdit.GrpcService/GetProperties',
                request_serializer=edit__service__pb2.GetPropertiesRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetPropertiesResponse.FromString,
                _registered_method=True)
        self.SetProperties = channel.unary_unary(
                '/SceneEdit.GrpcService/SetProperties',
                request_serializer=edit__service__pb2.SetPropertiesRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetPropertiesResponse.FromString,
                _registered_method=True)
        self.SetHighlightJoint = channel.unary_unary(
                '/SceneEdit.GrpcService/SetHighlightJoint',
                request_serializer=edit__service__pb2.SetHighlightJointRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetHighlightJointResponse.FromString,
                _registered_method=True)
        self.CustomCommand = channel.unary_unary(
                '/SceneEdit.GrpcService/CustomCommand',
                request_serializer=edit__service__pb2.CustomCommandRequest.SerializeToString,
                response_deserializer=edit__service__pb2.CustomCommandResponse.FromString,
                _registered_method=True)
        self.SetVisibility = channel.unary_unary(
                '/SceneEdit.GrpcService/SetVisibility',
                request_serializer=edit__service__pb2.SetVisibilityRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetVisibilityResponse.FromString,
                _registered_method=True)
        self.SetLock = channel.unary_unary(
                '/SceneEdit.GrpcService/SetLock',
                request_serializer=edit__service__pb2.SetLockRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetLockResponse.FromString,
                _registered_method=True)
        self.SetMoveRotateSensitivity = channel.unary_unary(
                '/SceneEdit.GrpcService/SetMoveRotateSensitivity',
                request_serializer=edit__service__pb2.SetMoveRotateSensitivityRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetMoveRotateSensitivityResponse.FromString,
                _registered_method=True)
        self.PublishScene = channel.unary_unary(
                '/SceneEdit.GrpcService/PublishScene',
                request_serializer=edit__service__pb2.PublishSceneRequest.SerializeToString,
                response_deserializer=edit__service__pb2.PublishSceneResponse.FromString,
                _registered_method=True)
        self.GetEntityHierarchy = channel.unary_unary(
                '/SceneEdit.GrpcService/GetEntityHierarchy',
                request_serializer=edit__service__pb2.GetEntityHierarchyRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetEntityHierarchyResponse.FromString,
                _registered_method=True)
        self.SetSelectedEntity = channel.unary_unary(
                '/SceneEdit.GrpcService/SetSelectedEntity',
                request_serializer=edit__service__pb2.SetSelectedEntityRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetSelectedEntityResponse.FromString,
                _registered_method=True)
        self.SetHighlightEntityTree = channel.unary_unary(
                '/SceneEdit.GrpcService/SetHighlightEntityTree',
                request_serializer=edit__service__pb2.SetHighlightEntityTreeRequest.SerializeToString,
                response_deserializer=edit__service__pb2.SetHighlightEntityTreeResponse.FromString,
                _registered_method=True)
        self.GetEntityPropertyGroups = channel.unary_unary(
                '/SceneEdit.GrpcService/GetEntityPropertyGroups',
                request_serializer=edit__service__pb2.GetEntityPropertyGroupsRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetEntityPropertyGroupsResponse.FromString,
                _registered_method=True)
        self.GetEntityPropertyGroupsBatch = channel.unary_unary(
                '/SceneEdit.GrpcService/GetEntityPropertyGroupsBatch',
                request_serializer=edit__service__pb2.GetEntityPropertyGroupsBatchRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetEntityPropertyGroupsBatchResponse.FromString,
                _registered_method=True)
        self.GetAllEntityPropertyGroups = channel.unary_unary(
                '/SceneEdit.GrpcService/GetAllEntityPropertyGroups',
                request_serializer=edit__service__pb2.GetAllEntityPropertyGroupsRequest.SerializeToString,
                response_deserializer=edit__service__pb2.GetAllEntityPropertyGroupsResponse.FromString,
                _registered_method=True)


class GrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Aloha(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddActorBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteActorBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingActorTransformBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActorTransformBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSyncFromMujocoToScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSyncFromMujocoToScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActorAssets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingSelectionChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingAddItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSelection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveActorBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWindowId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGeneratePos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCacheFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeSimState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeManipulatorType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCameraPNG(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActorAssetAabb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueueMouseEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueueMouseWheelEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueueKeyEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCameras(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActiveCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetViewportCameraTransform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCameraDataPNG(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPropertyGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPropertyGroupsBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetHighlightJoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CustomCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVisibility(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMoveRotateSensitivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntityHierarchy(self, request, context):
        """Entity hierarchy related RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSelectedEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetHighlightEntityTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntityPropertyGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntityPropertyGroupsBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllEntityPropertyGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Aloha': grpc.unary_unary_rpc_method_handler(
                    servicer.Aloha,
                    request_deserializer=edit__service__pb2.AlohaRequest.FromString,
                    response_serializer=edit__service__pb2.AlohaResponse.SerializeToString,
            ),
            'AddActorBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.AddActorBatch,
                    request_deserializer=edit__service__pb2.AddActorBatchRequest.FromString,
                    response_serializer=edit__service__pb2.AddActorBatchResponse.SerializeToString,
            ),
            'DeleteActorBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteActorBatch,
                    request_deserializer=edit__service__pb2.DeleteActorBatchRequest.FromString,
                    response_serializer=edit__service__pb2.DeleteActorBatchResponse.SerializeToString,
            ),
            'GetPendingOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingOperations,
                    request_deserializer=edit__service__pb2.GetPendingOperationsRequest.FromString,
                    response_serializer=edit__service__pb2.GetPendingOperationsResponse.SerializeToString,
            ),
            'GetPendingActorTransformBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingActorTransformBatch,
                    request_deserializer=edit__service__pb2.GetPendingActorTransformBatchRequest.FromString,
                    response_serializer=edit__service__pb2.GetPendingActorTransformBatchResponse.SerializeToString,
            ),
            'SetActorTransformBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActorTransformBatch,
                    request_deserializer=edit__service__pb2.SetActorTransformBatchRequest.FromString,
                    response_serializer=edit__service__pb2.SetActorTransformBatchResponse.SerializeToString,
            ),
            'GetSyncFromMujocoToScene': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSyncFromMujocoToScene,
                    request_deserializer=edit__service__pb2.GetSyncFromMujocoToSceneRequest.FromString,
                    response_serializer=edit__service__pb2.GetSyncFromMujocoToSceneResponse.SerializeToString,
            ),
            'SetSyncFromMujocoToScene': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSyncFromMujocoToScene,
                    request_deserializer=edit__service__pb2.SetSyncFromMujocoToSceneRequest.FromString,
                    response_serializer=edit__service__pb2.SetSyncFromMujocoToSceneResponse.SerializeToString,
            ),
            'ClearScene': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearScene,
                    request_deserializer=edit__service__pb2.ClearSceneRequest.FromString,
                    response_serializer=edit__service__pb2.ClearSceneResponse.SerializeToString,
            ),
            'GetActorAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActorAssets,
                    request_deserializer=edit__service__pb2.GetActorAssetsRequest.FromString,
                    response_serializer=edit__service__pb2.GetActorAssetsResponse.SerializeToString,
            ),
            'GetPendingSelectionChange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingSelectionChange,
                    request_deserializer=edit__service__pb2.GetPendingSelectionChangeRequest.FromString,
                    response_serializer=edit__service__pb2.GetPendingSelectionChangeResponse.SerializeToString,
            ),
            'GetPendingAddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingAddItem,
                    request_deserializer=edit__service__pb2.GetPendingAddItemRequest.FromString,
                    response_serializer=edit__service__pb2.GetPendingAddItemResponse.SerializeToString,
            ),
            'SetSelection': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSelection,
                    request_deserializer=edit__service__pb2.SetSelectionRequest.FromString,
                    response_serializer=edit__service__pb2.SetSelectionResponse.SerializeToString,
            ),
            'SaveState': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveState,
                    request_deserializer=edit__service__pb2.SaveStateRequest.FromString,
                    response_serializer=edit__service__pb2.SaveStateResponse.SerializeToString,
            ),
            'RestoreState': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreState,
                    request_deserializer=edit__service__pb2.RestoreStateRequest.FromString,
                    response_serializer=edit__service__pb2.RestoreStateResponse.SerializeToString,
            ),
            'RenameActor': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameActor,
                    request_deserializer=edit__service__pb2.RenameActorRequest.FromString,
                    response_serializer=edit__service__pb2.RenameActorResponse.SerializeToString,
            ),
            'MoveActorBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveActorBatch,
                    request_deserializer=edit__service__pb2.MoveActorBatchRequest.FromString,
                    response_serializer=edit__service__pb2.MoveActorBatchResponse.SerializeToString,
            ),
            'GetWindowId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWindowId,
                    request_deserializer=edit__service__pb2.GetWindowIdRequest.FromString,
                    response_serializer=edit__service__pb2.GetWindowIdResponse.SerializeToString,
            ),
            'GetGeneratePos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGeneratePos,
                    request_deserializer=edit__service__pb2.GetGeneratePosRequest.FromString,
                    response_serializer=edit__service__pb2.GetGeneratePosResponse.SerializeToString,
            ),
            'GetCacheFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCacheFolder,
                    request_deserializer=edit__service__pb2.GetCacheFolderRequest.FromString,
                    response_serializer=edit__service__pb2.GetCacheFolderResponse.SerializeToString,
            ),
            'LoadPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadPackage,
                    request_deserializer=edit__service__pb2.LoadPackageRequest.FromString,
                    response_serializer=edit__service__pb2.LoadPackageResponse.SerializeToString,
            ),
            'ChangeSimState': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeSimState,
                    request_deserializer=edit__service__pb2.ChangeSimStateRequest.FromString,
                    response_serializer=edit__service__pb2.ChangeSimStateResponse.SerializeToString,
            ),
            'ChangeManipulatorType': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeManipulatorType,
                    request_deserializer=edit__service__pb2.ChangeManipulatorTypeRequest.FromString,
                    response_serializer=edit__service__pb2.ChangeManipulatorTypeResponse.SerializeToString,
            ),
            'GetCameraPNG': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCameraPNG,
                    request_deserializer=edit__service__pb2.GetCameraPNGRequest.FromString,
                    response_serializer=edit__service__pb2.GetCameraPNGResponse.SerializeToString,
            ),
            'GetActorAssetAabb': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActorAssetAabb,
                    request_deserializer=edit__service__pb2.GetActorAssetAabbRequest.FromString,
                    response_serializer=edit__service__pb2.GetActorAssetAabbResponse.SerializeToString,
            ),
            'QueueMouseEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.QueueMouseEvent,
                    request_deserializer=edit__service__pb2.QueueMouseEventRequest.FromString,
                    response_serializer=edit__service__pb2.QueueMouseEventResponse.SerializeToString,
            ),
            'QueueMouseWheelEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.QueueMouseWheelEvent,
                    request_deserializer=edit__service__pb2.QueueMouseWheelEventRequest.FromString,
                    response_serializer=edit__service__pb2.QueueMouseWheelEventResponse.SerializeToString,
            ),
            'QueueKeyEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.QueueKeyEvent,
                    request_deserializer=edit__service__pb2.QueueKeyEventRequest.FromString,
                    response_serializer=edit__service__pb2.QueueKeyEventResponse.SerializeToString,
            ),
            'GetCameras': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCameras,
                    request_deserializer=edit__service__pb2.GetCamerasRequest.FromString,
                    response_serializer=edit__service__pb2.GetCamerasResponse.SerializeToString,
            ),
            'GetActiveCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveCamera,
                    request_deserializer=edit__service__pb2.GetActiveCameraRequest.FromString,
                    response_serializer=edit__service__pb2.GetActiveCameraResponse.SerializeToString,
            ),
            'SetActiveCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActiveCamera,
                    request_deserializer=edit__service__pb2.SetActiveCameraRequest.FromString,
                    response_serializer=edit__service__pb2.SetActiveCameraResponse.SerializeToString,
            ),
            'GetViewportCameraTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.GetViewportCameraTransform,
                    request_deserializer=edit__service__pb2.GetViewportCameraTransformRequest.FromString,
                    response_serializer=edit__service__pb2.GetViewportCameraTransformResponse.SerializeToString,
            ),
            'GetCameraDataPNG': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCameraDataPNG,
                    request_deserializer=edit__service__pb2.GetCameraDataPNGRequest.FromString,
                    response_serializer=edit__service__pb2.GetCameraDataPNGResponse.SerializeToString,
            ),
            'GetPropertyGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPropertyGroups,
                    request_deserializer=edit__service__pb2.GetPropertyGroupsRequest.FromString,
                    response_serializer=edit__service__pb2.GetPropertyGroupsResponse.SerializeToString,
            ),
            'GetPropertyGroupsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPropertyGroupsBatch,
                    request_deserializer=edit__service__pb2.GetPropertyGroupsBatchRequest.FromString,
                    response_serializer=edit__service__pb2.GetPropertyGroupsBatchResponse.SerializeToString,
            ),
            'GetProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperties,
                    request_deserializer=edit__service__pb2.GetPropertiesRequest.FromString,
                    response_serializer=edit__service__pb2.GetPropertiesResponse.SerializeToString,
            ),
            'SetProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProperties,
                    request_deserializer=edit__service__pb2.SetPropertiesRequest.FromString,
                    response_serializer=edit__service__pb2.SetPropertiesResponse.SerializeToString,
            ),
            'SetHighlightJoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHighlightJoint,
                    request_deserializer=edit__service__pb2.SetHighlightJointRequest.FromString,
                    response_serializer=edit__service__pb2.SetHighlightJointResponse.SerializeToString,
            ),
            'CustomCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.CustomCommand,
                    request_deserializer=edit__service__pb2.CustomCommandRequest.FromString,
                    response_serializer=edit__service__pb2.CustomCommandResponse.SerializeToString,
            ),
            'SetVisibility': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVisibility,
                    request_deserializer=edit__service__pb2.SetVisibilityRequest.FromString,
                    response_serializer=edit__service__pb2.SetVisibilityResponse.SerializeToString,
            ),
            'SetLock': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLock,
                    request_deserializer=edit__service__pb2.SetLockRequest.FromString,
                    response_serializer=edit__service__pb2.SetLockResponse.SerializeToString,
            ),
            'SetMoveRotateSensitivity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMoveRotateSensitivity,
                    request_deserializer=edit__service__pb2.SetMoveRotateSensitivityRequest.FromString,
                    response_serializer=edit__service__pb2.SetMoveRotateSensitivityResponse.SerializeToString,
            ),
            'PublishScene': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishScene,
                    request_deserializer=edit__service__pb2.PublishSceneRequest.FromString,
                    response_serializer=edit__service__pb2.PublishSceneResponse.SerializeToString,
            ),
            'GetEntityHierarchy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntityHierarchy,
                    request_deserializer=edit__service__pb2.GetEntityHierarchyRequest.FromString,
                    response_serializer=edit__service__pb2.GetEntityHierarchyResponse.SerializeToString,
            ),
            'SetSelectedEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSelectedEntity,
                    request_deserializer=edit__service__pb2.SetSelectedEntityRequest.FromString,
                    response_serializer=edit__service__pb2.SetSelectedEntityResponse.SerializeToString,
            ),
            'SetHighlightEntityTree': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHighlightEntityTree,
                    request_deserializer=edit__service__pb2.SetHighlightEntityTreeRequest.FromString,
                    response_serializer=edit__service__pb2.SetHighlightEntityTreeResponse.SerializeToString,
            ),
            'GetEntityPropertyGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntityPropertyGroups,
                    request_deserializer=edit__service__pb2.GetEntityPropertyGroupsRequest.FromString,
                    response_serializer=edit__service__pb2.GetEntityPropertyGroupsResponse.SerializeToString,
            ),
            'GetEntityPropertyGroupsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntityPropertyGroupsBatch,
                    request_deserializer=edit__service__pb2.GetEntityPropertyGroupsBatchRequest.FromString,
                    response_serializer=edit__service__pb2.GetEntityPropertyGroupsBatchResponse.SerializeToString,
            ),
            'GetAllEntityPropertyGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllEntityPropertyGroups,
                    request_deserializer=edit__service__pb2.GetAllEntityPropertyGroupsRequest.FromString,
                    response_serializer=edit__service__pb2.GetAllEntityPropertyGroupsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SceneEdit.GrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SceneEdit.GrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Aloha(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/Aloha',
            edit__service__pb2.AlohaRequest.SerializeToString,
            edit__service__pb2.AlohaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddActorBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/AddActorBatch',
            edit__service__pb2.AddActorBatchRequest.SerializeToString,
            edit__service__pb2.AddActorBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteActorBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/DeleteActorBatch',
            edit__service__pb2.DeleteActorBatchRequest.SerializeToString,
            edit__service__pb2.DeleteActorBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPendingOperations',
            edit__service__pb2.GetPendingOperationsRequest.SerializeToString,
            edit__service__pb2.GetPendingOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingActorTransformBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPendingActorTransformBatch',
            edit__service__pb2.GetPendingActorTransformBatchRequest.SerializeToString,
            edit__service__pb2.GetPendingActorTransformBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetActorTransformBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetActorTransformBatch',
            edit__service__pb2.SetActorTransformBatchRequest.SerializeToString,
            edit__service__pb2.SetActorTransformBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSyncFromMujocoToScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetSyncFromMujocoToScene',
            edit__service__pb2.GetSyncFromMujocoToSceneRequest.SerializeToString,
            edit__service__pb2.GetSyncFromMujocoToSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSyncFromMujocoToScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetSyncFromMujocoToScene',
            edit__service__pb2.SetSyncFromMujocoToSceneRequest.SerializeToString,
            edit__service__pb2.SetSyncFromMujocoToSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/ClearScene',
            edit__service__pb2.ClearSceneRequest.SerializeToString,
            edit__service__pb2.ClearSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActorAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetActorAssets',
            edit__service__pb2.GetActorAssetsRequest.SerializeToString,
            edit__service__pb2.GetActorAssetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingSelectionChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPendingSelectionChange',
            edit__service__pb2.GetPendingSelectionChangeRequest.SerializeToString,
            edit__service__pb2.GetPendingSelectionChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingAddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPendingAddItem',
            edit__service__pb2.GetPendingAddItemRequest.SerializeToString,
            edit__service__pb2.GetPendingAddItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSelection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetSelection',
            edit__service__pb2.SetSelectionRequest.SerializeToString,
            edit__service__pb2.SetSelectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SaveState',
            edit__service__pb2.SaveStateRequest.SerializeToString,
            edit__service__pb2.SaveStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/RestoreState',
            edit__service__pb2.RestoreStateRequest.SerializeToString,
            edit__service__pb2.RestoreStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/RenameActor',
            edit__service__pb2.RenameActorRequest.SerializeToString,
            edit__service__pb2.RenameActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveActorBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/MoveActorBatch',
            edit__service__pb2.MoveActorBatchRequest.SerializeToString,
            edit__service__pb2.MoveActorBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWindowId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetWindowId',
            edit__service__pb2.GetWindowIdRequest.SerializeToString,
            edit__service__pb2.GetWindowIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGeneratePos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetGeneratePos',
            edit__service__pb2.GetGeneratePosRequest.SerializeToString,
            edit__service__pb2.GetGeneratePosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCacheFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetCacheFolder',
            edit__service__pb2.GetCacheFolderRequest.SerializeToString,
            edit__service__pb2.GetCacheFolderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/LoadPackage',
            edit__service__pb2.LoadPackageRequest.SerializeToString,
            edit__service__pb2.LoadPackageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeSimState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/ChangeSimState',
            edit__service__pb2.ChangeSimStateRequest.SerializeToString,
            edit__service__pb2.ChangeSimStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeManipulatorType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/ChangeManipulatorType',
            edit__service__pb2.ChangeManipulatorTypeRequest.SerializeToString,
            edit__service__pb2.ChangeManipulatorTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCameraPNG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetCameraPNG',
            edit__service__pb2.GetCameraPNGRequest.SerializeToString,
            edit__service__pb2.GetCameraPNGResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActorAssetAabb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetActorAssetAabb',
            edit__service__pb2.GetActorAssetAabbRequest.SerializeToString,
            edit__service__pb2.GetActorAssetAabbResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueueMouseEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/QueueMouseEvent',
            edit__service__pb2.QueueMouseEventRequest.SerializeToString,
            edit__service__pb2.QueueMouseEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueueMouseWheelEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/QueueMouseWheelEvent',
            edit__service__pb2.QueueMouseWheelEventRequest.SerializeToString,
            edit__service__pb2.QueueMouseWheelEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueueKeyEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/QueueKeyEvent',
            edit__service__pb2.QueueKeyEventRequest.SerializeToString,
            edit__service__pb2.QueueKeyEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetCameras',
            edit__service__pb2.GetCamerasRequest.SerializeToString,
            edit__service__pb2.GetCamerasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetActiveCamera',
            edit__service__pb2.GetActiveCameraRequest.SerializeToString,
            edit__service__pb2.GetActiveCameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetActiveCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetActiveCamera',
            edit__service__pb2.SetActiveCameraRequest.SerializeToString,
            edit__service__pb2.SetActiveCameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetViewportCameraTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetViewportCameraTransform',
            edit__service__pb2.GetViewportCameraTransformRequest.SerializeToString,
            edit__service__pb2.GetViewportCameraTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCameraDataPNG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetCameraDataPNG',
            edit__service__pb2.GetCameraDataPNGRequest.SerializeToString,
            edit__service__pb2.GetCameraDataPNGResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPropertyGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPropertyGroups',
            edit__service__pb2.GetPropertyGroupsRequest.SerializeToString,
            edit__service__pb2.GetPropertyGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPropertyGroupsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetPropertyGroupsBatch',
            edit__service__pb2.GetPropertyGroupsBatchRequest.SerializeToString,
            edit__service__pb2.GetPropertyGroupsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetProperties',
            edit__service__pb2.GetPropertiesRequest.SerializeToString,
            edit__service__pb2.GetPropertiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetProperties',
            edit__service__pb2.SetPropertiesRequest.SerializeToString,
            edit__service__pb2.SetPropertiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetHighlightJoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetHighlightJoint',
            edit__service__pb2.SetHighlightJointRequest.SerializeToString,
            edit__service__pb2.SetHighlightJointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CustomCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/CustomCommand',
            edit__service__pb2.CustomCommandRequest.SerializeToString,
            edit__service__pb2.CustomCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVisibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetVisibility',
            edit__service__pb2.SetVisibilityRequest.SerializeToString,
            edit__service__pb2.SetVisibilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetLock',
            edit__service__pb2.SetLockRequest.SerializeToString,
            edit__service__pb2.SetLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMoveRotateSensitivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetMoveRotateSensitivity',
            edit__service__pb2.SetMoveRotateSensitivityRequest.SerializeToString,
            edit__service__pb2.SetMoveRotateSensitivityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/PublishScene',
            edit__service__pb2.PublishSceneRequest.SerializeToString,
            edit__service__pb2.PublishSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntityHierarchy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetEntityHierarchy',
            edit__service__pb2.GetEntityHierarchyRequest.SerializeToString,
            edit__service__pb2.GetEntityHierarchyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSelectedEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetSelectedEntity',
            edit__service__pb2.SetSelectedEntityRequest.SerializeToString,
            edit__service__pb2.SetSelectedEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetHighlightEntityTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/SetHighlightEntityTree',
            edit__service__pb2.SetHighlightEntityTreeRequest.SerializeToString,
            edit__service__pb2.SetHighlightEntityTreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntityPropertyGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetEntityPropertyGroups',
            edit__service__pb2.GetEntityPropertyGroupsRequest.SerializeToString,
            edit__service__pb2.GetEntityPropertyGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntityPropertyGroupsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetEntityPropertyGroupsBatch',
            edit__service__pb2.GetEntityPropertyGroupsBatchRequest.SerializeToString,
            edit__service__pb2.GetEntityPropertyGroupsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllEntityPropertyGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SceneEdit.GrpcService/GetAllEntityPropertyGroups',
            edit__service__pb2.GetAllEntityPropertyGroupsRequest.SerializeToString,
            edit__service__pb2.GetAllEntityPropertyGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
